"""update profile table

Revision ID: 7366d1cdb61d
Revises: 568d175f4644
Create Date: 2023-11-23 22:22:17.578011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7366d1cdb61d"
down_revision: Union[str, None] = "568d175f4644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("last_name", sa.String(length=40), nullable=True)
    )
    op.drop_column("profiles", "last_first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column("last_first_name", sa.VARCHAR(length=40), nullable=True),
    )
    op.drop_column("profiles", "last_name")
    # ### end Alembic commands ###
